name: Booking-API Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  # Manual trigger via “Run workflow” button
  workflow_dispatch: {}
  # Automatically trigger on pushes to the dev branch
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Preview environment variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
